### ISSUE TITLE
계획서 및 PPT 작성

### ISSUE THREAD

**Issue by BEOKS** [Video-Streaming-Pipeline/Video-Streaming-Pipeline#1]
계획서 : https://docs.google.com/document/d/1zVOcM5_kXifl1TfbrYVSRFJXO1keDw0t4gVgN4jJPH4/edit?usp=sharing
PPT : https://docs.google.com/presentation/d/1e-xWlMts3DoW_A98I06usSD7nCjz5pW7QGu135NAsuM/edit?usp=sharing

@justinjoy 안녕하세요 매니저님, 계획서와 PPT초안이 작성되어서 말씀드립니다.
부족한 부분에 대해서 리뷰해주시면 감사드리겠습니다!!

**Comment by justinjoy** [comment]
큰 오류는 없어보이네요. 발표 잘 하시길!
