### ISSUE TITLE
춘계학술대회

### ISSUE THREAD

**Issue by justinjoy** [Video-Streaming-Pipeline/Video-Streaming-Pipeline#2]
오늘보니 업데이트 된 것이 있어 링크 첨부합니다.

 - http://kips.or.kr/bbs/sn/article/1611

기타 다른 학회 일정도 확인하여 제출할 계획을 세워보세요.

**Comment by BEOKS** [comment]
감사합니다!
저희가 계획서를 마무리하는 중인데 
논문 제출 마감이 3월 26일까지 되어있는데 빠듯하지 않을까 걱정됩니다.

**Comment by hyoeun98** [comment]
한국IT서비스학회 http://www.itservice.or.kr/news01.html?bmode=read&bid=news&id_no=686&l=1 (6.2, 논문 초록 4.9마감)

한국 통신학회 https://www.kics.or.kr/html/?pmode=inputList&smode=view&part=&intAcSeq=578 (6.16~6.18, 상세 정보는 아직 공지되지 않음)

한국 차세대 컴퓨팅학회 http://www.kingpc.or.kr/wp/?uid=336&mod=document&page_id=3350 (5.13~5.15, 논문 4.2마감)

한국 정보 기술학회 https://www.ki-it.or.kr/%EA%B3%B5%EC%A7%80%EC%82%AC%ED%95%AD/8541016 (6.3~6.5, 일반/대학생 구분, 세부 사항 추후 공지)

한국 정보 과학회 http://kiise.or.kr/conference/kcc/2021/ (6.23~6.25, 학부생과 고등학생/일반 구분,논문 4.23 마감)

논문 제출 일정 고려하여 추려보았습니다.

**Comment by justinjoy** [comment]
요행을 바라는 것은 아니지만, 학술대회 제출일은 연장되기도하니 그렇게 빡빡한 일정은 아닐거에요. 제출 요건도 확인해보세요. 초록과 최종 논문을 나누어서 제출하는 경우도 많습니다.

**Comment by hyoeun98** [comment]
한국 정보 기술 학회 / 논문 투고 & 사전 등록 마감 5.17 / 개최 기간 6.3 ~ 6.5
이상의 일정으로 추진해보겠습니다.
