### ISSUE TITLE
bitstream error

### ISSUE THREAD

**Issue by hymi54** [Video-Streaming-Pipeline/Video-Streaming-Pipeline#28]
@BEOKS 
[gst-1.18] pi@raspberrypi:~/Video-Streaming-Pipeline/raspi $ python3 raspicamview_with_bitstream.py 
[ WARN:0] global /home/pi/opencv-master/modules/videoio/src/cap_gstreamer.cpp (1044) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global /home/pi/opencv-master/modules/videoio/src/cap_gstreamer.cpp (1081) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
Sending Time=162252554044.41144ms, frmae number=0
Sending Time=162252554090.42255ms, frmae number=1
Sending Time=162252554128.56052ms, frmae number=2
Sending Time=162252554168.7009ms, frmae number=3
Sending Time=162252554207.5537ms, frmae number=4
Sending Time=162252554248.18295ms, frmae number=5
Sending Time=162252554286.1502ms, frmae number=6
Sending Time=162252554324.02255ms, frmae number=7
Sending Time=162252554361.7173ms, frmae number=8
Sending Time=162252554401.82596ms, frmae number=9
Sending Time=162252554440.1807ms, frmae number=10
Sending Time=162252554478.49768ms, frmae number=11
Sending Time=162252554518.68576ms, frmae number=12
Sending Time=162252554560.24698ms, frmae number=13
Sending Time=162252554596.72705ms, frmae number=14
Sending Time=162252554635.46906ms, frmae number=15
Sending Time=162252554673.82437ms, frmae number=16
Sending Time=162252554713.81372ms, frmae number=17
Sending Time=162252554752.06738ms, frmae number=18
Sending Time=162252554790.54767ms, frmae number=19
Sending Time=162252554828.60727ms, frmae number=20
Sending Time=162252554867.36707ms, frmae number=21
Sending Time=162252554905.63406ms, frmae number=22
Sending Time=162252554944.1906ms, frmae number=23
Sending Time=162252554982.5727ms, frmae number=24
Sending Time=162252555021.49445ms, frmae number=25
Sending Time=162252555060.41113ms, frmae number=26
Sending Time=162252555098.22842ms, frmae number=27
Sending Time=162252555137.24252ms, frmae number=28
Sending Time=162252555174.83667ms, frmae number=29
Sending Time=162252555213.44333ms, frmae number=30
Sending Time=162252555252.2953ms, frmae number=31
Sending Time=162252555290.63785ms, frmae number=32
다시 받지를 못하네 저 에러랑 관련이있을라나

**Comment by BEOKS** [comment]
포트 번호가 달라서 그런듯 둘다 9778로 코드 변경했는데 다시 실행 해봐

**Comment by BEOKS** [comment]
서버 파일도 순서 변경해서둘 다 pull해서 실행하는걸 추천함

**Comment by hymi54** [comment]
> [ WARN:0] global /home/pi/opencv-master/modules/videoio/src/cap_gstreamer.cpp (1044) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global /home/pi/opencv-master/modules/videoio/src/cap_gstreamer.cpp (1081) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
Sending Time=162253000534.31497ms, frmae number=0
Sending Time=162253000582.53244ms, frmae number=1
Sending Time=162253000620.67252ms, frmae number=2
Sending Time=162253000661.4665ms, frmae number=3
Sending Time=162253000700.1422ms, frmae number=4
Sending Time=162253000741.15433ms, frmae number=5
Sending Time=162253000778.5211ms, frmae number=6
Sending Time=162253000817.5999ms, frmae number=7
Sending Time=162253000855.72855ms, frmae number=8
Sending Time=162253000895.32443ms, frmae number=9
Sending Time=162253000934.66006ms, frmae number=10
Receiving Prcoess finished
Sending Time=162253000975.05133ms, frmae number=11
Sending Time=162253001012.35284ms, frmae number=12
Sending Time=162253001049.6167ms, frmae number=13
Sending Time=162253001087.57166ms, frmae number=14

라즈베리파이에서 여기까지 출력 후 멈춤

**Comment by hymi54** [comment]
> (pipeline_1) PS D:\Git\repos\Video-Streaming-Pipeline> & C:/Users/LeeHyunMin/anaconda3/envs/pipeline_1/python.exe d:/Git/repos/Video-Streaming-Pipeline/python/benchmark_with_streaming_bitstream.py -m 1
Cuda avilable NVIDIA GeForce RTX 3080
[ WARN:0] global C:\opencv\sources\modules\videoio\src\cap_gstreamer.cpp (1081) cv::GStreamerCapture::open OpenCV | GStreamer warning: Cannot query video position: status=1, value=122, duration=-1
Client connected :  ('192.168.0.14', 56264)
Traceback (most recent call last):
  File "d:/Git/repos/Video-Streaming-Pipeline/python/benchmark_with_streaming_bitstream.py", line 100, in <module>
    data=pickle.dump(predictions)
TypeError: dump() missing required argument 'file' (pos 2)

 PC쪽 오류

**Comment by BEOKS** [comment]
Method 잘못 호출해서 생기는 에러인듯 수정했으니 확인바람

**Comment by hymi54** [comment]
> [ WARN:0] global /home/pi/opencv-master/modules/videoio/src/cap_gstreamer.cpp (1044) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global /home/pi/opencv-master/modules/videoio/src/cap_gstreamer.cpp (1081) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
Sending Time=162253425544.91104ms, frmae number=0
Sending Time=162253425591.51508ms, frmae number=1
Sending Time=162253425630.3876ms, frmae number=2
Sending Time=162253425670.03525ms, frmae number=3
Sending Time=162253425709.02222ms, frmae number=4
Sending Time=162253425750.70026ms, frmae number=5
Sending Time=162253425788.67792ms, frmae number=6
Sending Time=162253425827.54028ms, frmae number=7
Receiving Time=162253425858.68347ms,Frame Number : 0
Sending Time=162253425869.24857ms, frmae number=8
Sending Time=162253425907.2989ms, frmae number=9
Sending Time=162253425952.70538ms, frmae number=10
Sending Time=162253425992.27185ms, frmae number=11
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "raspicamview_with_bitstream.py", line 55, in receive
    data=pickle.loads(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/storage.py", line 161, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 772, in _legacy_load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 728, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Sending Time=162253426032.27206ms, frmae number=12
Sending Time=162253426072.14154ms, frmae number=13
Sending Time=162253426111.03857ms, frmae number=14

1번 수신 성공

**Comment by BEOKS** [comment]
cuda용으로 저장된 데이터를 그대로 변환해서 생기는 오류인듯 변환관련해서 주석했으니 파일 둘다 pull해서 확인바람, 내가 실행 못하니까 화나네

**Comment by hymi54** [comment]
> [ WARN:0] global C:\opencv\sources\modules\videoio\src\cap_gstreamer.cpp (1081) cv::GStreamerCapture::open OpenCV | GStreamer warning: Cannot query video position: status=1, value=270, duration=-1
Client connected :  ('192.168.0.14', 56306)
Traceback (most recent call last):
  File "d:/Git/repos/Video-Streaming-Pipeline/python/benchmark_with_streaming_bitstream.py", line 100, in <module>
    data=pickle.dumps(predictions.numpy())
AttributeError: 'list' object has no attribute 'numpy'

PC 에러

**Comment by BEOKS** [comment]
numpy()삭제
