### ISSUE TITLE
한국통신학회 제출 논문 수정

### ISSUE THREAD

**Issue by BEOKS** [Video-Streaming-Pipeline/Video-Streaming-Pipeline#29]
https://1drv.ms/w/s!AvwH5EGkmL5BhiyRdfFEXS0TIxpV

@justinjoy 저희 논문 초안을 작성해봤습니다. 메모로 리뷰해주시만 감사드릴것 같습니다!
(글꼴의 경우 word에 이슈가 있어서 마지막에 통일할 예정입니다.)

**Comment by justinjoy** [comment]
잘 작성하였네요. 메모 참고해서 수정하면 좋을 듯 하네요. :)

**Comment by BEOKS** [comment]
넵 감사합니다!
