### ISSUE TITLE
benchmark err

### ISSUE THREAD

**Issue by hyoeun98** [Video-Streaming-Pipeline/Video-Streaming-Pipeline#9]
RuntimeError: [enforce fail at CPUAllocator.cpp:47] ((ptrdiff_t)nbytes) >= 0. alloc_cpu() seems to have been called with negative number: 3699376128

AttributeError: module 'torchvision.models' has no attribute 'mobilenet_v3_large'
- mobilenet_v2 is possible, but v3 is not

**Comment by BEOKS** [comment]
> AttributeError: module 'torchvision.models' has no attribute 'mobilenet_v3_large'

위 경우에는 torchvision 업데이트 한 번 해주셈 (```pip install torchvision```)

> RuntimeError: [enforce fail at CPUAllocator.cpp:47] ((ptrdiff_t)nbytes) >= 0. alloc_cpu() seems to have been called with negative number: 3699376128

이건언제 에러가 발생한거야?

**Comment by hyoeun98** [comment]
batchsize = 1 로 설정하여 해결
